title: "Kreativ Werkstatt Reimer"
baseURL: "https://kreativ-werkstatt-reimer.de/"
metaDataFormat: "yaml"
disableKinds:
  - taxonomy

enableEmoji: true
enableRobotsTXT: true
enableGitInfo: true

defaultContentLanguage: "de"
languageCode: "de-DE"
languageName: "German (Germany)"

menu:
  footer:
  - identifier: facebook
    name: Facebook
    url: https://facebook.com/KreativWerkstattReimer/

sitemap:
  changeFreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

params:
  env: production
