name: Deploy

on:
  push:	
    branches:	
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v4
      - name: "🧰 Install Hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.59.1
          extended: true
      - name: "🧰 Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: 8.16.x
      - name: "🧰 Install Yarn"
        run: npm install -g yarn
      - name: "🧰 Install asset dependencies"
        run: |
          cd assets
          yarn install
      - name: "🏗 Build"
        run: hugo
      - name: "🚀 Deploy to Uberspace"
        uses: appleboy/scp-action@v0.1.7
        with:
          username: kwr
          host: jedicke.uberspace.de
          key: ${{ secrets.DEPLOY_KEY }}
          source: public
          strip_components: 1
          rm: true
          target: ${{ secrets.DEPLOY_TARGET_PATH }}
